In [1]:
import numpy as np

In [2]:
v1=np.array([1,2,3])
v1

array([1, 2, 3])

In [3]:
v2=np.array([4,5,6])
v2

array([4, 5, 6])

In [8]:
v1=np.array([1,2,3]).reshape(-1,1)
v1

array([[1],
       [2],
       [3]])

In [9]:
v2=np.array([4,5,6]).reshape(-1,1)
v2

array([[4],
       [5],
       [6]])

In [10]:
v1.T

array([[1, 2, 3]])

In [11]:
v1.T.T

array([[1],
       [2],
       [3]])

In [12]:
v1.T.T.T

array([[1, 2, 3]])

In [14]:
v3=np.array([4,5]).reshape(-1,1)
v3

array([[4],
       [5]])

In [13]:
v1 * v2

array([[ 4],
       [10],
       [18]])

In [15]:
v1 * v3

ValueError: operands could not be broadcast together with shapes (3,1) (2,1) 

In [16]:
v3=np.array([4]).reshape(-1,1)
v3

array([[4]])

In [17]:
v1 * v3

array([[ 4],
       [ 8],
       [12]])

In [18]:
v1 * v2.T

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

In [21]:
v1_broadcast = np.concatenate((v1,v1,v1),axis = 1)
v1_broadcast

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [22]:
v2_broadcast = np.concatenate((v2.T,v2.T,v2.T))
v2_broadcast

array([[4, 5, 6],
       [4, 5, 6],
       [4, 5, 6]])

In [23]:
v1_broadcast * v2_broadcast

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

In [26]:
np.dot(v1.T, v2)

array([[32]])

In [27]:
1*4 + 2*5 + 3*6

32

In [28]:
def practice():
    size = np.random.randint(1,5)
    a = np.random.randint(-3,4,size).reshape(-1,1)
    b = np.random.randint(-3,4,size).reshape(-1,1)
    print("a = ")
    print(a)
    print()
    print("b = ")
    print(b)
    print()
    answer = int(input("What is np.dot(a.T,b), as a scalar?  "))
    print()
    expected = np.dot(a.T, b)[0][0]
    if answer == expected:
        print("Good job!")
        return True
    else:
        print("\nActually, it is ", expected)
        print("Calculation:", " + ".join(f"({x}*{y})" for x,y in zip(a.reshape(-1), b.reshape(-1))))
        time.sleep(2)
        return False

goal = 5
correct = 0
while correct < goal:
    print("="*40)
    print(f"Get {goal-correct} in a row correct to finish!")
    print("="*40)
    print()
    if practice():
        correct += 1
    else:
        correct = 0
    print()
        
print(f"Nice, you got {goal} in a row correct!")

Get 5 in a row correct to finish!

a = 
[[3]]

b = 
[[1]]

What is np.dot(a.T,b), as a scalar?  3

Good job!

Get 4 in a row correct to finish!

a = 
[[2]]

b = 
[[2]]

What is np.dot(a.T,b), as a scalar?  4

Good job!

Get 3 in a row correct to finish!

a = 
[[ 0]
 [-2]
 [-2]]

b = 
[[ 2]
 [-3]
 [ 1]]

What is np.dot(a.T,b), as a scalar?  4

Good job!

Get 2 in a row correct to finish!

a = 
[[-3]
 [ 0]
 [-2]
 [-2]]

b = 
[[-2]
 [-1]
 [-3]
 [ 3]]

What is np.dot(a.T,b), as a scalar?  6

Good job!

Get 1 in a row correct to finish!

a = 
[[ 0]
 [-2]
 [-2]]

b = 
[[ 0]
 [ 2]
 [-2]]

What is np.dot(a.T,b), as a scalar?  0

Good job!

Nice, you got 5 in a row correct!


In [29]:
import pandas as pd

In [32]:
houses = pd.DataFrame([[2,1,1985],[3,1,1998],[4,3,2005],[4,2,2020]], columns=['beds','baths','year'])
houses

beds  baths  year
0     2      1  1985
1     3      1  1998
2     4      3  2005
3     4      2  2020

In [37]:
def predict_price(house):
    return((house["beds"]*42.3)+(house['baths']*10)+(house['year']*1.67)-3213)
houses.iloc[0]

beds        2
baths       1
year     1985
Name: 0, dtype: int64

In [38]:
predict_price(houses.iloc[0])

196.54999999999973

In [39]:
predict_price(houses.iloc[1])

260.55999999999995

In [40]:
predict_price(houses.iloc[2])

334.5499999999997

In [42]:
#coefficients
x = np.array([42.3, 10, 1.67]).reshape(-1,1)
b = -3213
x

array([[42.3 ],
       [10.  ],
       [ 1.67]])

In [45]:
A = houses.values
A

array([[   2,    1, 1985],
       [   3,    1, 1998],
       [   4,    3, 2005],
       [   4,    2, 2020]])

In [50]:
h0 = A[0:1,:]
h1 = A[1:2,:]
h2 = A[2:3,:]
h3 = A[3:4,:]
h3

array([[   4,    2, 2020]])

In [51]:
np.dot(h0,x)+b

array([[196.55]])

In [52]:
predict_price(houses.iloc[0])

196.54999999999973

In [61]:
houses['const'] =1
A = houses.values
h0 = A[0:1,:]
h1 = A[1:2,:]
h2 = A[2:3,:]
h3 = A[3:4,:]
houses

beds  baths  year  const
0     2      1  1985      1
1     3      1  1998      1
2     4      3  2005      1
3     4      2  2020      1

In [62]:
x = np.array([42.3, 10, 1.67, -3213]).reshape(-1,1)
x

array([[ 4.230e+01],
       [ 1.000e+01],
       [ 1.670e+00],
       [-3.213e+03]])

In [63]:
np.dot(h0, x)

array([[196.55]])

In [64]:
np.dot(h1, x)

array([[260.56]])

In [65]:
np.dot(h2, x)

array([[334.55]])

In [66]:
np.dot(h3, x)

array([[349.6]])

In [69]:
A

array([[   2,    1, 1985,    1],
       [   3,    1, 1998,    1],
       [   4,    3, 2005,    1],
       [   4,    2, 2020,    1]])

In [68]:
x

array([[ 4.230e+01],
       [ 1.000e+01],
       [ 1.670e+00],
       [-3.213e+03]])

In [70]:
np.dot(A,x)

array([[196.55],
       [260.56],
       [334.55],
       [349.6 ]])

In [71]:
houses["price_est"]=np.dot(A,x)

In [72]:
houses

beds  baths  year  const  price_est
0     2      1  1985      1     196.55
1     3      1  1998      1     260.56
2     4      3  2005      1     334.55
3     4      2  2020      1     349.60

In [73]:
def practice(cols):
    rows = np.random.randint(3, 7)
    A = np.random.randint(-3,4,(rows, cols))
    b = np.random.randint(-3,4,cols).reshape(-1,1)
    print("A = ")
    print(A)
    print()
    print("b = ")
    print(b)
    print()
    M = np.dot(A,b).astype(object)
    pos = np.random.randint(0,rows)
    expected, M[pos,0] = M[pos,0], "x"
    print("np.dot(A,b) = ")
    print(M)    
    print()
    answer = int(input("What is 'x'?  "))
    print()
    if answer == expected:
        print("Good job!")
        return True
    else:
        print("\nActually, it is ", expected)
        print("Calculation:", " + ".join(f"({x}*{y})" for x,y in zip(A[pos].reshape(-1), b.reshape(-1))))
        time.sleep(2)
        return False

goal = 3
correct = 0
while correct < goal:
    print("="*40)
    print(f"Get {goal-correct} in a row correct to finish!")
    print("="*40)
    print()
    if practice(correct+2):
        correct += 1
    else:
        correct = 0
    print()
        
print(f"Nice, you got {goal} in a row correct!")

Get 3 in a row correct to finish!

A = 
[[ 0  2]
 [-1  3]
 [-2  0]
 [-1  3]
 [-1 -3]]

b = 
[[ 1]
 [-1]]

np.dot(A,b) = 
[[-2]
 [-4]
 ['x']
 [-4]
 [2]]

What is 'x'?  -2

Good job!

Get 2 in a row correct to finish!

A = 
[[-1  3 -1]
 [-2  2 -1]
 [ 3 -1 -1]
 [-2  2 -2]
 [ 0  1  2]]

b = 
[[ 2]
 [ 1]
 [-2]]

np.dot(A,b) = 
[[3]
 [0]
 [7]
 [2]
 ['x']]

What is 'x'?  -3

Good job!

Get 1 in a row correct to finish!

A = 
[[ 3  0  1 -2]
 [-1  1  0  2]
 [ 2  1  0 -3]]

b = 
[[1]
 [0]
 [3]
 [3]]

np.dot(A,b) = 
[['x']
 [5]
 [-7]]

What is 'x'?  0

Good job!

Nice, you got 3 in a row correct!


Part3

In [75]:
houses = pd.DataFrame([[2,1,1985],[3,1,1998],[4,3,2005],[4,2,2020]], columns=['beds','baths','year'])
houses["price"]=np.dot(A,x)
houses

beds  baths  year   price
0     2      1  1985  196.55
1     3      1  1998  260.56
2     4      3  2005  334.55
3     4      2  2020  349.60

In [86]:
A = houses.values[:,:-1]
A = np.concatenate((A, np.ones(4).reshape(-1,1)), axis=1)
A

array([[2.000e+00, 1.000e+00, 1.985e+03, 1.000e+00],
       [3.000e+00, 1.000e+00, 1.998e+03, 1.000e+00],
       [4.000e+00, 3.000e+00, 2.005e+03, 1.000e+00],
       [4.000e+00, 2.000e+00, 2.020e+03, 1.000e+00]])

In [87]:
b =houses.values[:,-1:]
b

array([[196.55],
       [260.56],
       [334.55],
       [349.6 ]])

In [89]:
x = np.linalg.solve(A, b)
x

array([[ 4.230e+01],
       [ 1.000e+01],
       [ 1.670e+00],
       [-3.213e+03]])

In [90]:
list(x)

[array([42.3]), array([10.]), array([1.67]), array([-3213.])]

In [91]:
A = np.array([
    [10,0,1],
    [2,8,1],
    [4,4,1],
])
b = np.array([7,5,5]).reshape(-1,1)

x = np.linalg.solve(A, b)
apple_val, banana_val, basket_val = x.reshape(-1)

print("Apple Value:", apple_val)
print("Banana Value:", banana_val)
print("Basket Value:", basket_val)

Apple Value: 0.5
Banana Value: 0.24999999999999994
Basket Value: 2.0
