In [1]:
import numpy as np
a = np.array([
    [0,0,5,8],
    [1,2,4,8],
    [2,4,6,9],
])

In [3]:
a % 2

array([[0, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 1]])

In [4]:
a % 2 == 0

array([[ True,  True, False,  True],
       [False,  True,  True,  True],
       [ True,  True,  True, False]])

In [5]:
(a % 2 == 0).astype(int)

array([[1, 1, 0, 1],
       [0, 1, 1, 1],
       [1, 1, 1, 0]])

In [6]:
(a % 2 == 0).astype(int).sum()

9

In [7]:
(a % 2 == 0).astype(int).mean() * 100

75.0